/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (1.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Sun Apr 20 14:33:40 2025


#include "CanBusBroker_ParamsParser.h"
#include <yarp/os/LogStream.h>
#include <yarp/os/Value.h>

namespace {
    YARP_LOG_COMPONENT(CanBusBrokerParamsCOMPONENT, "yarp.device.CanBusBroker")
}


CanBusBroker_ParamsParser::CanBusBroker_ParamsParser()
{
}


std::vector<std::string> CanBusBroker_ParamsParser::getListOfParams() const
{
    std::vector<std::string> params;
    params.push_back("buses");
    params.push_back("syncPeriod");
    return params;
}


bool      CanBusBroker_ParamsParser::parseParams(const yarp::os::Searchable & config)
{
    //Check for --help option
    if (config.check("help"))
    {
        yCInfo(CanBusBrokerParamsCOMPONENT) << getDocumentationOfDeviceParams();
    }

    std::string config_string = config.toString();
    yarp::os::Property prop_check(config_string.c_str());
    //Parser of parameter buses
    {
        if (config.check("buses"))
        {
            {
                m_buses.clear();
                yarp::os::Bottle* tempBot = config.find("buses").asList();
                if (tempBot)
                {
                    std::string tempBots = tempBot->toString();
                    for (size_t i=0; i<tempBot->size(); i++)
                    {
                        m_buses.push_back(tempBot->get(i).asString());
                    }
                }
                else
                {
                     yCError(CanBusBrokerParamsCOMPONENT) <<"parameter 'buses' is not a properly formatted bottle";
                }
            }
            yCInfo(CanBusBrokerParamsCOMPONENT) << "Parameter 'buses' using value:" << m_buses;
        }
        else
        {
            yCError(CanBusBrokerParamsCOMPONENT) << "Mandatory parameter 'buses' not found!";
            yCError(CanBusBrokerParamsCOMPONENT) << "Description of the parameter: CAN buses";
            return false;
        }
        prop_check.unput("buses");
    }

    //Parser of parameter syncPeriod
    {
        if (config.check("syncPeriod"))
        {
            m_syncPeriod = config.find("syncPeriod").asFloat64();
            yCInfo(CanBusBrokerParamsCOMPONENT) << "Parameter 'syncPeriod' using value:" << m_syncPeriod;
        }
        else
        {
            yCInfo(CanBusBrokerParamsCOMPONENT) << "Parameter 'syncPeriod' using DEFAULT value:" << m_syncPeriod;
        }
        prop_check.unput("syncPeriod");
    }

    /*
    //This code check if the user set some parameter which are not check by the parser
    //If the parser is set in strict mode, this will generate an error
    if (prop_check.size() > 0)
    {
        bool extra_params_found = false;
        for (auto it=prop_check.begin(); it!=prop_check.end(); it++)
        {
            if (m_parser_is_strict)
            {
                yCError(CanBusBrokerParamsCOMPONENT) << "User asking for parameter: "<<it->name <<" which is unknown to this parser!";
                extra_params_found = true;
            }
            else
            {
                yCWarning(CanBusBrokerParamsCOMPONENT) << "User asking for parameter: "<< it->name <<" which is unknown to this parser!";
            }
        }

       if (m_parser_is_strict && extra_params_found)
       {
           return false;
       }
    }
    */
    return true;
}


std::string      CanBusBroker_ParamsParser::getDocumentationOfDeviceParams() const
{
    std::string doc;
    doc = doc + std::string("\n=============================================\n");
    doc = doc + std::string("This is the help for device: CanBusBroker\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("This is the list of the parameters accepted by the device:\n");
    doc = doc + std::string("'buses': CAN buses\n");
    doc = doc + std::string("'syncPeriod': synchronization period\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("Here are some examples of invocation command with yarpdev, with all params:\n");
    doc = doc + " yarpdev --device CanBusBroker --buses <mandatory_value> --syncPeriod 0.0\n";
    doc = doc + std::string("Using only mandatory params:\n");
    doc = doc + " yarpdev --device CanBusBroker --buses <mandatory_value>\n";
    doc = doc + std::string("=============================================\n\n");    return doc;
}
