#ifndef __CAN_BUS_BROKER_LOG_COMPONENT_HPP__
#define __CAN_BUS_BROKER_LOG_COMPONENT_HPP__

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(CBB)

#endif // __CAN_BUS_BROKER_LOG_COMPONENT_HPP__
