#ifndef __CAN_BUS_SOCKET_LOG_COMPONENT_HPP__
#define __CAN_BUS_SOCKET_LOG_COMPONENT_HPP__

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(SCK)

#endif // __CAN_BUS_SOCKET_LOG_COMPONENT_HPP__
