#ifndef __JOINT_CALIBRATOR_LOG_COMPONENT_HPP__
#define __JOINT_CALIBRATOR_LOG_COMPONENT_HPP__

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(JC)

#endif // __JOINT_CALIBRATOR_LOG_COMPONENT_HPP__
