#ifndef __PHIDGET_SPATIAL_LOG_COMPONENT_HPP__
#define __PHIDGET_SPATIAL_LOG_COMPONENT_HPP__

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(PHSP)

#endif // __PHIDGET_SPATIAL_LOG_COMPONENT_HPP__
