#ifndef __TECHNOSOFT_IPOS_LOG_COMPONENT_HPP__
#define __TECHNOSOFT_IPOS_LOG_COMPONENT_HPP__

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(IPOS)

#endif // __TECHNOSOFT_IPOS_LOG_COMPONENT_HPP__
