#ifndef __JR3_MBED_LOG_COMPONENT_HPP__
#define __JR3_MBED_LOG_COMPONENT_HPP__

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(JR3M)
YARP_DECLARE_LOG_COMPONENT(JR3M_QUIET)

#endif // __JR3_MBED_LOG_COMPONENT_HPP__
