#ifndef __DEXTRA_RAW_CONTROL_BOARD_LOG_COMPONENT_HPP__
#define __DEXTRA_RAW_CONTROL_BOARD_LOG_COMPONENT_HPP__

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(DEXTRA)

#endif // __DEXTRA_RAW_CONTROL_BOARD_LOG_COMPONENT_HPP__
