/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (1.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Sun Apr 20 14:33:40 2025


#include "LacqueyFetch_ParamsParser.h"
#include <yarp/os/LogStream.h>
#include <yarp/os/Value.h>

namespace {
    YARP_LOG_COMPONENT(LacqueyFetchParamsCOMPONENT, "yarp.device.LacqueyFetch")
}


LacqueyFetch_ParamsParser::LacqueyFetch_ParamsParser()
{
}


std::vector<std::string> LacqueyFetch_ParamsParser::getListOfParams() const
{
    std::vector<std::string> params;
    params.push_back("canId");
    params.push_back("name");
    return params;
}


bool      LacqueyFetch_ParamsParser::parseParams(const yarp::os::Searchable & config)
{
    //Check for --help option
    if (config.check("help"))
    {
        yCInfo(LacqueyFetchParamsCOMPONENT) << getDocumentationOfDeviceParams();
    }

    std::string config_string = config.toString();
    yarp::os::Property prop_check(config_string.c_str());
    //Parser of parameter canId
    {
        if (config.check("canId"))
        {
            m_canId = config.find("canId").asInt64();
            yCInfo(LacqueyFetchParamsCOMPONENT) << "Parameter 'canId' using value:" << m_canId;
        }
        else
        {
            yCError(LacqueyFetchParamsCOMPONENT) << "Mandatory parameter 'canId' not found!";
            yCError(LacqueyFetchParamsCOMPONENT) << "Description of the parameter: CAN bus ID";
            return false;
        }
        prop_check.unput("canId");
    }

    //Parser of parameter name
    {
        if (config.check("name"))
        {
            m_name = config.find("name").asString();
            yCInfo(LacqueyFetchParamsCOMPONENT) << "Parameter 'name' using value:" << m_name;
        }
        else
        {
            yCError(LacqueyFetchParamsCOMPONENT) << "Mandatory parameter 'name' not found!";
            yCError(LacqueyFetchParamsCOMPONENT) << "Description of the parameter: axis name";
            return false;
        }
        prop_check.unput("name");
    }

    /*
    //This code check if the user set some parameter which are not check by the parser
    //If the parser is set in strict mode, this will generate an error
    if (prop_check.size() > 0)
    {
        bool extra_params_found = false;
        for (auto it=prop_check.begin(); it!=prop_check.end(); it++)
        {
            if (m_parser_is_strict)
            {
                yCError(LacqueyFetchParamsCOMPONENT) << "User asking for parameter: "<<it->name <<" which is unknown to this parser!";
                extra_params_found = true;
            }
            else
            {
                yCWarning(LacqueyFetchParamsCOMPONENT) << "User asking for parameter: "<< it->name <<" which is unknown to this parser!";
            }
        }

       if (m_parser_is_strict && extra_params_found)
       {
           return false;
       }
    }
    */
    return true;
}


std::string      LacqueyFetch_ParamsParser::getDocumentationOfDeviceParams() const
{
    std::string doc;
    doc = doc + std::string("\n=============================================\n");
    doc = doc + std::string("This is the help for device: LacqueyFetch\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("This is the list of the parameters accepted by the device:\n");
    doc = doc + std::string("'canId': CAN bus ID\n");
    doc = doc + std::string("'name': axis name\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("Here are some examples of invocation command with yarpdev, with all params:\n");
    doc = doc + " yarpdev --device LacqueyFetch --canId <mandatory_value> --name <mandatory_value>\n";
    doc = doc + std::string("Using only mandatory params:\n");
    doc = doc + " yarpdev --device LacqueyFetch --canId <mandatory_value> --name <mandatory_value>\n";
    doc = doc + std::string("=============================================\n\n");    return doc;
}
