#ifndef __WIIMOTE_SENSOR_LOG_COMPONENT_HPP__
#define __WIIMOTE_SENSOR_LOG_COMPONENT_HPP__

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(WII)

#endif // __WIIMOTE_SENSOR_LOG_COMPONENT_HPP__
