#ifndef __FORCE_TORQUE_CAN_LOG_COMPONENT_HPP__
#define __FORCE_TORQUE_CAN_LOG_COMPONENT_HPP__

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(FTC)

#endif // __FORCE_TORQUE_CAN_LOG_COMPONENT_HPP__
