#ifndef __LEAP_MOTION_SENSOR_LOG_COMPONENT_HPP__
#define __LEAP_MOTION_SENSOR_LOG_COMPONENT_HPP__

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(LEAP)

#endif // __LEAP_MOTION_SENSOR_LOG_COMPONENT_HPP__
