/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (1.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Sun Apr 20 14:33:40 2025


#ifndef JR3PCI_PARAMSPARSER_H
#define JR3PCI_PARAMSPARSER_H

#include <yarp/os/Searchable.h>
#include <yarp/dev/IDeviceDriverParams.h>
#include <string>
#include <cmath>

/**
* This class is the parameters parser for class Jr3Pci.
*
* These are the used parameters:
* | Group name | Parameter name | Type           | Units | Default Value     | Required | Description                       | Notes |
* |:----------:|:--------------:|:--------------:|:-----:|:-----------------:|:--------:|:---------------------------------:|:-----:|
* | -          | names          | vector<string> | -     | (ch0 ch1 ch2 ch3) | 0        | sensor names                      | -     |
* | -          | filter         | int            | -     | 0                 | 0        | filter ID                         | [0-6] |
* | -          | levogyrate     | bool           | -     | false             | 0        | assume levogyrate XYZ coordinates | -     |
*
* The device can be launched by yarpdev using one of the following examples (with and without all optional parameters):
* \code{.unparsed}
* yarpdev --device Jr3Pci --names \" (ch0 ch1 ch2 ch3) \" --filter 0 --levogyrate false
* \endcode
*
* \code{.unparsed}
* yarpdev --device Jr3Pci
* \endcode
*
*/

class Jr3Pci_ParamsParser : public yarp::dev::IDeviceDriverParams
{
public:
    Jr3Pci_ParamsParser();
    ~Jr3Pci_ParamsParser() override = default;

public:
    const std::string m_device_classname = {"Jr3Pci"};
    const std::string m_device_name = {"Jr3Pci"};
    bool m_parser_is_strict = false;
    struct parser_version_type
    {
         int major = 1;
         int minor = 0;
    };
    const parser_version_type m_parser_version = {};

    const std::string m_names_defaultValue = {"(ch0 ch1 ch2 ch3)"};
    const std::string m_filter_defaultValue = {"0"};
    const std::string m_levogyrate_defaultValue = {"false"};

    std::vector<std::string> m_names = { }; //Default values for lists are managed in the class constructor. It is highly recommended to provide a suggested value also for optional string parameters.
    int m_filter = {0};
    bool m_levogyrate = {false};

    bool          parseParams(const yarp::os::Searchable & config) override;
    std::string   getDeviceClassName() const override { return m_device_classname; }
    std::string   getDeviceName() const override { return m_device_name; }
    std::string   getDocumentationOfDeviceParams() const override;
    std::vector<std::string> getListOfParams() const override;
};

#endif
