#ifndef __EMULATED_CONTROL_BOARD_LOG_COMPONENT_HPP__
#define __EMULATED_CONTROL_BOARD_LOG_COMPONENT_HPP__

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(ECB)

#endif // __EMULATED_CONTROL_BOARD_LOG_COMPONENT_HPP__
