/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (1.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Sun Apr 20 14:33:40 2025


#include "CuiAbsolute_ParamsParser.h"
#include <yarp/os/LogStream.h>
#include <yarp/os/Value.h>

namespace {
    YARP_LOG_COMPONENT(CuiAbsoluteParamsCOMPONENT, "yarp.device.CuiAbsolute")
}


CuiAbsolute_ParamsParser::CuiAbsolute_ParamsParser()
{
}


std::vector<std::string> CuiAbsolute_ParamsParser::getListOfParams() const
{
    std::vector<std::string> params;
    params.push_back("canId");
    params.push_back("reverse");
    params.push_back("timeout");
    params.push_back("maxRetries");
    params.push_back("mode");
    params.push_back("pushDelay");
    return params;
}


bool      CuiAbsolute_ParamsParser::parseParams(const yarp::os::Searchable & config)
{
    //Check for --help option
    if (config.check("help"))
    {
        yCInfo(CuiAbsoluteParamsCOMPONENT) << getDocumentationOfDeviceParams();
    }

    std::string config_string = config.toString();
    yarp::os::Property prop_check(config_string.c_str());
    //Parser of parameter canId
    {
        if (config.check("canId"))
        {
            m_canId = config.find("canId").asInt64();
            yCInfo(CuiAbsoluteParamsCOMPONENT) << "Parameter 'canId' using value:" << m_canId;
        }
        else
        {
            yCError(CuiAbsoluteParamsCOMPONENT) << "Mandatory parameter 'canId' not found!";
            yCError(CuiAbsoluteParamsCOMPONENT) << "Description of the parameter: CAN bus ID";
            return false;
        }
        prop_check.unput("canId");
    }

    //Parser of parameter reverse
    {
        if (config.check("reverse"))
        {
            m_reverse = config.find("reverse").asBool();
            yCInfo(CuiAbsoluteParamsCOMPONENT) << "Parameter 'reverse' using value:" << m_reverse;
        }
        else
        {
            yCError(CuiAbsoluteParamsCOMPONENT) << "Mandatory parameter 'reverse' not found!";
            yCError(CuiAbsoluteParamsCOMPONENT) << "Description of the parameter: reverse counting";
            return false;
        }
        prop_check.unput("reverse");
    }

    //Parser of parameter timeout
    {
        if (config.check("timeout"))
        {
            m_timeout = config.find("timeout").asFloat64();
            yCInfo(CuiAbsoluteParamsCOMPONENT) << "Parameter 'timeout' using value:" << m_timeout;
        }
        else
        {
            yCInfo(CuiAbsoluteParamsCOMPONENT) << "Parameter 'timeout' using DEFAULT value:" << m_timeout;
        }
        prop_check.unput("timeout");
    }

    //Parser of parameter maxRetries
    {
        if (config.check("maxRetries"))
        {
            m_maxRetries = config.find("maxRetries").asInt64();
            yCInfo(CuiAbsoluteParamsCOMPONENT) << "Parameter 'maxRetries' using value:" << m_maxRetries;
        }
        else
        {
            yCInfo(CuiAbsoluteParamsCOMPONENT) << "Parameter 'maxRetries' using DEFAULT value:" << m_maxRetries;
        }
        prop_check.unput("maxRetries");
    }

    //Parser of parameter mode
    {
        if (config.check("mode"))
        {
            m_mode = config.find("mode").asString();
            yCInfo(CuiAbsoluteParamsCOMPONENT) << "Parameter 'mode' using value:" << m_mode;
        }
        else
        {
            yCError(CuiAbsoluteParamsCOMPONENT) << "Mandatory parameter 'mode' not found!";
            yCError(CuiAbsoluteParamsCOMPONENT) << "Description of the parameter: publish mode";
            return false;
        }
        prop_check.unput("mode");
    }

    //Parser of parameter pushDelay
    {
        if (config.check("pushDelay"))
        {
            m_pushDelay = config.find("pushDelay").asInt64();
            yCInfo(CuiAbsoluteParamsCOMPONENT) << "Parameter 'pushDelay' using value:" << m_pushDelay;
        }
        else
        {
            yCInfo(CuiAbsoluteParamsCOMPONENT) << "Parameter 'pushDelay' using DEFAULT value:" << m_pushDelay;
        }
        prop_check.unput("pushDelay");
    }

    /*
    //This code check if the user set some parameter which are not check by the parser
    //If the parser is set in strict mode, this will generate an error
    if (prop_check.size() > 0)
    {
        bool extra_params_found = false;
        for (auto it=prop_check.begin(); it!=prop_check.end(); it++)
        {
            if (m_parser_is_strict)
            {
                yCError(CuiAbsoluteParamsCOMPONENT) << "User asking for parameter: "<<it->name <<" which is unknown to this parser!";
                extra_params_found = true;
            }
            else
            {
                yCWarning(CuiAbsoluteParamsCOMPONENT) << "User asking for parameter: "<< it->name <<" which is unknown to this parser!";
            }
        }

       if (m_parser_is_strict && extra_params_found)
       {
           return false;
       }
    }
    */
    return true;
}


std::string      CuiAbsolute_ParamsParser::getDocumentationOfDeviceParams() const
{
    std::string doc;
    doc = doc + std::string("\n=============================================\n");
    doc = doc + std::string("This is the help for device: CuiAbsolute\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("This is the list of the parameters accepted by the device:\n");
    doc = doc + std::string("'canId': CAN bus ID\n");
    doc = doc + std::string("'reverse': reverse counting\n");
    doc = doc + std::string("'timeout': acquisition timeout\n");
    doc = doc + std::string("'maxRetries': maximum number of retries on timeout\n");
    doc = doc + std::string("'mode': publish mode\n");
    doc = doc + std::string("'pushDelay': push mode delay\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("Here are some examples of invocation command with yarpdev, with all params:\n");
    doc = doc + " yarpdev --device CuiAbsolute --canId <mandatory_value> --reverse <mandatory_value> --timeout 0.25 --maxRetries 10 --mode <mandatory_value> --pushDelay 0\n";
    doc = doc + std::string("Using only mandatory params:\n");
    doc = doc + " yarpdev --device CuiAbsolute --canId <mandatory_value> --reverse <mandatory_value> --mode <mandatory_value>\n";
    doc = doc + std::string("=============================================\n\n");    return doc;
}
