#ifndef __AMOR_CONTROL_BOARD_LOG_COMPONENT_HPP__
#define __AMOR_CONTROL_BOARD_LOG_COMPONENT_HPP__

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(AMOR)

#endif // __AMOR_CONTROL_BOARD_LOG_COMPONENT_HPP__
