#ifndef __TEXTILES_HAND_LOG_COMPONENT_HPP__
#define __TEXTILES_HAND_LOG_COMPONENT_HPP__

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(TXT)

#endif // __TEXTILES_HAND_LOG_COMPONENT_HPP__
