#ifndef __QB_ROBOTICS_CONTROL_BOARD_LOG_COMPONENT_HPP__
#define __QB_ROBOTICS_CONTROL_BOARD_LOG_COMPONENT_HPP__

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(QBROB)

#endif // __QB_ROBOTICS_CONTROL_BOARD_LOG_COMPONENT_HPP__
