#ifndef __SPACE_NAVIGATOR_LOG_COMPONENT_HPP__
#define __SPACE_NAVIGATOR_LOG_COMPONENT_HPP__

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(SPNAV)

#endif // __SPACE_NAVIGATOR_LOG_COMPONENT_HPP__
